matrix:
  include:
    - os: linux
      sudo: required
      dist: precise
      language: python
      install:
        - pip install -r requirements.txt
      python:
        - "2.7"
        - "3.6"
      script:
        - py.test -v
    - os: linux
      sudo: required
      dist: trusty
      language: python
      install:
        - pip install -r requirements.txt
      python:
        - "2.7"
        - "3.6"
      script:
        - py.test -v
