matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - py.test -v
