language: python
sudo: required
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - bash extra/install_sqlite_for_ubuntu.bash
script:
  - python check_fts5.py
  - py.test
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always